apiVersion: v1
kind: Pod
metadata:
  labels:
    name: "jenkins-agent"    
spec:
  containers:
  - name: helm
    image: dtzar/helm-kubectl:3.2.0
    tty: true
    securityContext:
      privileged: true
  - name: docker
    image: docker:19.03.8-dind
    tty: true
    securityContext:
      privileged: true
