apiVersion: v1
kind: Pod
metadata:
  labels:
    name: "jenkins-agent"    
spec:
  containers:
  - name: docker
    image: dtzar/helm-kubectl:3.1.2
    tty: true
    securityContext:
      privileged: true
    livenessProbe:
      failureThreshold: 12
      httpGet:
        path: /login
        port: http
        scheme: HTTP
      initialDelaySeconds: 30
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    readinessProbe:
      failureThreshold: 12
      httpGet:
        path: /login
        port: http
        scheme: HTTP
      initialDelaySeconds: 30
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5

