apiVersion: v1
kind: Pod
metadata:
  labels:
    name: "jenkins-agent"    
spec:
  containers:
  - name: docker
    image: dtzar/helm-kubectl:3.1.2
    tty: true
    securityContext:
      privileged: true
